### ISSUE TITLE
KeyError: 'source_user_iden'

### ISSUE THREAD

**Issue by anujitbhu** [yausername/whatsapp-cli#4]
Hi I am able to create user But I am not able to send messages ..Please suggest 

```
`[root@wpace whatsapp-cli]# whatsapp-cli --token o.hthBzj5dm7oAHMMFzEV users
Sandeep Srivastava
[root@wpace whatsapp-cli]# whatsapp-cli --token o.hthBzj5dm7oAHMMFzEV send -u '919999977481' -m 'Hello test'
Traceback (most recent call last):
  File "/bin/whatsapp-cli", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/whatsappCli/__main__.py", line 4, in main
    cli(obj={})
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/whatsappCli/ui/cli.py", line 29, in send
    feeder.post(user, message)
  File "/usr/lib/python2.7/site-packages/whatsappCli/feed/pb_feeder.py", line 53, in post
    req["push"]["source_user_iden"] = config["source_user_iden"]
KeyError: 'source_user_iden'
[root@wpace whatsapp-cli]# whatsapp-cli --token o.hthBzj5dm7oAHMMFzEV send -u 'Sandeep Srivastava' -m 'Hello test'
Traceback (most recent call last):
  File "/bin/whatsapp-cli", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/whatsappCli/__main__.py", line 4, in main
    cli(obj={})
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/whatsappCli/ui/cli.py", line 29, in send
    feeder.post(user, message)
  File "/usr/lib/python2.7/site-packages/whatsappCli/feed/pb_feeder.py", line 53, in post
    req["push"]["source_user_iden"] = config["source_user_iden"]
KeyError: 'source_user_iden'
`
```
Please suggest the issue. 

Thks 

Anuj

**Comment by yausername** [comment]
This things is very limited in what it can do. 

- To be able to send messages you need to receive at least one message after starting the application for seeding the conf (default location ~/.whatsapp-cli/conf).
  `whatsapp-cli --token <token>`

- You cannot initiate chat with users from whom you have not received a notification in the recent past. This is a pushbullet limitation as it uses reply to notification to send messages. I need to explore on using whatsapp web instead of pushbullet.

Thanks

**Comment by yausername** [comment]
Also you should not be sharing tokens like that in the open.

**Comment by anujitbhu** [comment]
That token is not the actual one. 
Yes, we need to explore something else other than Pushbullet I think so .

**Comment by yausername** [comment]
I haven't tried but this one looks promising https://github.com/zvovov/whatsapp-web

**Comment by yausername** [comment]
Feel free to fork this repo if you have any ideas.
